# Generated by Django 2.1.2 on 2018-10-10 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('born', models.DateField()),
                ('died', models.DateField(blank=True, null=True)),
                ('biogrphy', models.TextField()),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('born', models.DateField()),
                ('died', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Genera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('plot', models.TextField(blank=True, max_length=120)),
                ('length', models.IntegerField()),
                ('ratings', models.PositiveIntegerField(default=0)),
                ('year', models.DateField(blank=True, null=True)),
                ('review1', models.TextField(blank=True)),
                ('review2', models.TextField(blank=True)),
                ('review3', models.TextField(blank=True)),
                ('view', models.PositiveIntegerField(blank=True, default=0)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('image2', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('image3', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Actor')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Category')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Director')),
                ('genera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Genera')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Writter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('born', models.DateField()),
                ('died', models.DateField(blank=True, null=True)),
                ('biogrphy', models.TextField()),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Writter'),
        ),
    ]
