# Generated by Django 2.1.2 on 2018-10-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20181010_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
