# Generated by Django 2.1.2 on 2018-10-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20181011_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('HollyWood', 'Hollywood'), ('BollyWood', 'Bollywood'), ('Indian_Bangla', 'Indian_bangla'), ('Tamil', 'TamiL'), ('Indian_ohers', 'Indian_other'), ('Bangladesh', 'BangLadesh'), ('Foreign', 'Foreign')], default='HollyWood', max_length=120),
        ),
    ]
