# Generated by Django 2.1.2 on 2018-10-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20181011_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='genera',
            name='name',
            field=models.CharField(choices=[('Action', 'Action'), ('Sci-Fi', 'Sci-Fi'), ('Drama', 'Drama'), ('Adventure', 'Adventure'), ('Romantic', 'Romantic'), ('Horor', 'Horor'), ('Thriller', 'Foreign')], default='Action', max_length=120),
        ),
    ]
