# Generated by Django 2.1.2 on 2018-10-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20181016_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='movie.Actor'),
        ),
    ]
