# Generated by Django 2.1.2 on 2018-10-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20181016_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genera',
        ),
        migrations.AddField(
            model_name='movie',
            name='genera',
            field=models.ManyToManyField(related_name='genera', to='movie.Genera'),
        ),
    ]
