# Generated by Django 2.1.2 on 2018-10-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20181016_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='biography',
            field=models.TextField(null=True),
        ),
    ]
